[[mgr.prepend_keymap]]
on = [ "<S-Up>" ]
run = "seek -1" 
desc = "Peek up 5 units in the preview" 

[[mgr.prepend_keymap]]
on = [ "<S-Down>" ]
run = "seek 1"
desc = "Peek down 5 units in the preview"

[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell in the current directory"

[[mgr.prepend_keymap]]
on   = ["g", "r"]
run  = "plugin cd-git-root"
desc = "Go to git repo root"
# Bookmarks plugin
[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"

# Copy file contents plugin
[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

# Code Editor plugin
[[mgr.prepend_keymap]]
on   = [ "c", "o" ]
run  = "plugin open-code-editor"
desc = "Open In Code Editor"

# Lazygit plugin
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"


# Bypass plugin
[[mgr.prepend_keymap]]
on = [ "L" ]
run = "plugin bypass"
desc = "Recursively enter child directory, skipping children with only a single subdirectory"

[[mgr.prepend_keymap]]
on = [ "H" ]
run = "plugin bypass --args=reverse"
desc = "Recursively enter parent directory, skipping parents with only a single subdirectory"

[[mgr.prepend_keymap]]
on = [ "l" ]
run = "plugin bypass --args=smart_enter"
desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory"

# Max-preview plugin
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on = [ "\"", "h" ]
run = "plugin custom-shell --args=history"
desc = "Show Custom-shell history"
